[settings_window_main.window_coords]
h = 1100
w = 400
x = 100
y = 100

[settings_window_main.window_name]
file = "file1.py"
icon = "icon1.ico"
name = "main window"

[settings_window_set_comp.window_coords]
h = 400
w = 400
x = 100
y = 100

[settings_window_set_comp.window_name]
file = "file1.py"
icon = "icon2.ico"
name = "settings window competition"

[settings_window_set_soft.window_coords]
h = 400
w = 400
x = 100
y = 100

[settings_window_set_soft.window_name]
file = "file1.py"
icon = "icon3.ico"
name = "settings window software"
