[settings_window_main]
window_coords_h = 475
window_coords_w = 1030
window_coords_x = 329
window_coords_y = 297

[settings_soft]
emergency_exit = false
CLUB_ID = "1A2B-3C4D-5E6F"
SOFT_LAST_OPEN = "1980-06-30"
COMP_DATA_COMPETITION = "2022-02-24"
screen_resolution_x = 1920
screen_resolution_y = 1080

[competition_action]
COMP_q_tur = 2
COMP_q_period = 4
COMP_q_zone = 2
COMP_q_anglers = 15

[misc]
