[settings_window_main]
window_coords_h = 485
window_coords_w = 1231
window_coords_x = 61
window_coords_y = 138
window_name = "Название главного окна"

[settings_soft]
emergency_exit = true
file_settings_soft = "fish_settings.toml"
screen_resolution_x = 1366
screen_resolution_y = 768
CLUB_ID = "1A2B-3C4D-5E6F"
SOFT_DB_FILE = "db_competition.db"
SOFT_LAST_OPEN = "1980-06-30"
COMP_DATA_COMPETITION = "2022-02-24"

[settings_window_set_comp]
window_name = "Название окна настроек соревнований"
window_coords_h = 400
window_coords_w = 400
window_coords_x = 61
window_coords_y = 138

[settings_window_about]
window_name = "Название окна о программе"
window_coords_h = 400
window_coords_w = 400
window_coords_x = 100
window_coords_y = 100

[settings_window_set_soft]
window_name = "Название окна настроек программы"
window_coords_h = 400
window_coords_w = 400
window_coords_x = 61
window_coords_y = 138
