[settings_window_main]
window_coords_h = 300
window_coords_w = 865
window_coords_x = 212
window_coords_y = 142

[settings_soft]
screen_resolution_x = 1366
screen_resolution_y = 768

[competition_action]
COMP_q_tur = 2
COMP_q_period = 2
COMP_q_zone = 2
COMP_q_anglers = 6

[misc]
