[settings_window_main]
window_coords_h = 350
window_coords_w = 720
window_coords_x = 662
window_coords_y = 559

[settings_soft]
screen_resolution_x = 1920
screen_resolution_y = 1080

[competition_action]
COMP_q_tur = 1
COMP_q_period = 3
COMP_q_zone = 1
COMP_q_anglers = 8

[misc]
