[settings_window_main]
window_coords_h = 350
window_coords_w = 1030
window_coords_x = 443
window_coords_y = 379

[settings_soft]
screen_resolution_x = 1920
screen_resolution_y = 1080

[competition_action]
COMP_q_tur = 2
COMP_q_period = 4
COMP_q_zone = 2
COMP_q_anglers = 8

[misc]
