[settings_window_main]
window_coords_h = 570
window_coords_w = 674
window_coords_x = 735
window_coords_y = 219
window_name = "Название главного окна"

[settings_window_set_comp]
window_coords_h = 400
window_coords_w = 400
window_coords_x = 735
window_coords_y = 219
window_name = "Название окна настроек соревнований"

[settings_window_set_soft]
window_coords_h = 400
window_coords_w = 400
window_coords_x = 735
window_coords_y = 219
window_name = "Название окна настроек программы"

[settings_window_about]
window_coords_h = 400
window_coords_w = 400
window_coords_x = 100
window_coords_y = 100
window_name = "Название окна о программе"

[settings_soft]
emergency_exit = true
file_settings_soft = "fish_settings.toml"
screen_resolution_x = 1920
screen_resolution_y = 1080
