import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sportik_number_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_number_.setGeometry(QtCore.QRect(5, 70, 40, 20))
        self.Sportik_number_.setObjectName("Sportik_number_")
        self.Sportik_fio_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_fio_.setGeometry(QtCore.QRect(130, 70, 180, 20))
        self.Sportik_fio_.setObjectName("Sportik_fio_")
        self.Sportik_period1_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_period1_.setGeometry(QtCore.QRect(800, 70, 40, 20))
        self.Sportik_period1_.setObjectName("Sportik_period1_")
        self.Sportik_period2_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_period2_.setGeometry(QtCore.QRect(860, 70, 40, 20))
        self.Sportik_period2_.setObjectName("Sportik_period2_")
        self.Sportik_period3_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_period3_.setGeometry(QtCore.QRect(915, 70, 40, 20))
        self.Sportik_period3_.setObjectName("Sportik_period3_")
        self.Sportik_period4_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_period4_.setGeometry(QtCore.QRect(980, 70, 40, 20))
        self.Sportik_period4_.setObjectName("Sportik_period4_")
        self.Sportik_zona1_ = QtWidgets.QComboBox(self.centralwidget)
        self.Sportik_zona1_.setGeometry(QtCore.QRect(620, 70, 70, 20))
        self.Sportik_zona1_.setObjectName("Sportik_zona1_")
        self.Sportik_zona1_.addItem("")
        self.Sportik_zona1_.addItem("")
        self.Sportik_zona1_.addItem("")
        self.Sportik_zona2_ = QtWidgets.QComboBox(self.centralwidget)
        self.Sportik_zona2_.setGeometry(QtCore.QRect(710, 70, 70, 20))
        self.Sportik_zona2_.setObjectName("Sportik_zona2_")
        self.Sportik_zona2_.addItem("")
        self.Sportik_zona2_.addItem("")
        self.Sportik_zona2_.addItem("")
        self.checkBox_number_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_number_.setGeometry(QtCore.QRect(5, 20, 40, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_number_.sizePolicy().hasHeightForWidth())
        self.checkBox_number_.setSizePolicy(sizePolicy)
        self.checkBox_number_.setText("")
        self.checkBox_number_.setChecked(False)
        self.checkBox_number_.setObjectName("checkBox_number_")
        self.checkBox_fio_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_fio_.setGeometry(QtCore.QRect(130, 20, 180, 20))
        self.checkBox_fio_.setText("")
        self.checkBox_fio_.setChecked(False)
        self.checkBox_fio_.setObjectName("checkBox_fio_")
        self.checkBox_zona1_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_zona1_.setGeometry(QtCore.QRect(620, 20, 70, 20))
        self.checkBox_zona1_.setText("")
        self.checkBox_zona1_.setChecked(False)
        self.checkBox_zona1_.setObjectName("checkBox_zona1_")
        self.checkBox_zona2_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_zona2_.setGeometry(QtCore.QRect(710, 20, 70, 20))
        self.checkBox_zona2_.setText("")
        self.checkBox_zona2_.setChecked(False)
        self.checkBox_zona2_.setObjectName("checkBox_zona2_")
        self.checkBox_period1_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_period1_.setGeometry(QtCore.QRect(800, 20, 40, 20))
        self.checkBox_period1_.setText("")
        self.checkBox_period1_.setChecked(False)
        self.checkBox_period1_.setObjectName("checkBox_period1_")
        self.checkBox_period2_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_period2_.setGeometry(QtCore.QRect(860, 20, 40, 20))
        self.checkBox_period2_.setText("")
        self.checkBox_period2_.setChecked(False)
        self.checkBox_period2_.setObjectName("checkBox_period2_")
        self.checkBox_period3_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_period3_.setGeometry(QtCore.QRect(915, 20, 40, 20))
        self.checkBox_period3_.setText("")
        self.checkBox_period3_.setChecked(False)
        self.checkBox_period3_.setObjectName("checkBox_period3_")
        self.checkBox_period4_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_period4_.setGeometry(QtCore.QRect(980, 20, 40, 20))
        self.checkBox_period4_.setText("")
        self.checkBox_period4_.setChecked(False)
        self.checkBox_period4_.setObjectName("checkBox_period4_")
        self.Sportik_points_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_points_.setGeometry(QtCore.QRect(1040, 70, 40, 20))
        self.Sportik_points_.setObjectName("Sportik_points_")
        self.Sportik_team_place_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_team_place_.setGeometry(QtCore.QRect(1160, 70, 40, 20))
        self.Sportik_team_place_.setObjectName("Sportik_team_place_")
        self.checkBox_points_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_points_.setGeometry(QtCore.QRect(1040, 20, 40, 20))
        self.checkBox_points_.setText("")
        self.checkBox_points_.setChecked(False)
        self.checkBox_points_.setObjectName("checkBox_points_")
        self.checkBox_team_place_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_team_place_.setGeometry(QtCore.QRect(1160, 20, 40, 20))
        self.checkBox_team_place_.setText("")
        self.checkBox_team_place_.setChecked(False)
        self.checkBox_team_place_.setObjectName("checkBox_team_place_")
        self.checkBox_team_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_team_.setGeometry(QtCore.QRect(330, 20, 180, 20))
        self.checkBox_team_.setText("")
        self.checkBox_team_.setChecked(False)
        self.checkBox_team_.setObjectName("checkBox_team_")
        self.Sportik_team_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_team_.setGeometry(QtCore.QRect(330, 70, 180, 20))
        self.Sportik_team_.setObjectName("Sportik_team_")
        self.checkBox_rank_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rank_.setGeometry(QtCore.QRect(550, 20, 40, 20))
        self.checkBox_rank_.setText("")
        self.checkBox_rank_.setChecked(False)
        self.checkBox_rank_.setObjectName("checkBox_rank_")
        self.Sportik_rank_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_rank_.setGeometry(QtCore.QRect(550, 70, 40, 20))
        self.Sportik_rank_.setObjectName("Sportik_rank_")
        self.Sportik_lottery_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_lottery_.setGeometry(QtCore.QRect(65, 70, 40, 20))
        self.Sportik_lottery_.setObjectName("Sportik_lottery_")
        self.checkBox_lottery_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_lottery_.setGeometry(QtCore.QRect(65, 20, 40, 20))
        self.checkBox_lottery_.setText("")
        self.checkBox_lottery_.setChecked(False)
        self.checkBox_lottery_.setObjectName("checkBox_lottery_")
        self.label_number_ = QtWidgets.QLabel(self.centralwidget)
        self.label_number_.setGeometry(QtCore.QRect(5, 40, 40, 20))
        self.label_number_.setObjectName("label_number_")
        self.label_lottery_ = QtWidgets.QLabel(self.centralwidget)
        self.label_lottery_.setGeometry(QtCore.QRect(65, 40, 40, 20))
        self.label_lottery_.setObjectName("label_lottery_")
        self.label_fio_ = QtWidgets.QLabel(self.centralwidget)
        self.label_fio_.setGeometry(QtCore.QRect(130, 40, 180, 20))
        self.label_fio_.setObjectName("label_fio_")
        self.label_team_ = QtWidgets.QLabel(self.centralwidget)
        self.label_team_.setGeometry(QtCore.QRect(330, 40, 180, 20))
        self.label_team_.setObjectName("label_team_")
        self.label_rank_ = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_.setGeometry(QtCore.QRect(550, 40, 40, 20))
        self.label_rank_.setObjectName("label_rank_")
        self.label_zona1_ = QtWidgets.QLabel(self.centralwidget)
        self.label_zona1_.setGeometry(QtCore.QRect(620, 40, 70, 20))
        self.label_zona1_.setObjectName("label_zona1_")
        self.label_zona2_ = QtWidgets.QLabel(self.centralwidget)
        self.label_zona2_.setGeometry(QtCore.QRect(710, 40, 70, 20))
        self.label_zona2_.setObjectName("label_zona2_")
        self.label_period1_ = QtWidgets.QLabel(self.centralwidget)
        self.label_period1_.setGeometry(QtCore.QRect(800, 40, 40, 20))
        self.label_period1_.setObjectName("label_period1_")
        self.label_period2_ = QtWidgets.QLabel(self.centralwidget)
        self.label_period2_.setGeometry(QtCore.QRect(860, 40, 40, 20))
        self.label_period2_.setObjectName("label_period2_")
        self.label_period3_ = QtWidgets.QLabel(self.centralwidget)
        self.label_period3_.setGeometry(QtCore.QRect(915, 40, 40, 20))
        self.label_period3_.setObjectName("label_period3_")
        self.label_period4_ = QtWidgets.QLabel(self.centralwidget)
        self.label_period4_.setGeometry(QtCore.QRect(980, 40, 40, 20))
        self.label_period4_.setObjectName("label_period4_")
        self.label_points_ = QtWidgets.QLabel(self.centralwidget)
        self.label_points_.setGeometry(QtCore.QRect(1040, 40, 40, 20))
        self.label_points_.setObjectName("label_points_")
        self.label_team_place_ = QtWidgets.QLabel(self.centralwidget)
        self.label_team_place_.setGeometry(QtCore.QRect(1160, 40, 40, 20))
        self.label_team_place_.setObjectName("label_team_place_")
        self.label_self_place_ = QtWidgets.QLabel(self.centralwidget)
        self.label_self_place_.setGeometry(QtCore.QRect(1100, 40, 40, 20))
        self.label_self_place_.setObjectName("label_self_place_")
        self.Sportik_self_place_ = QtWidgets.QLineEdit(self.centralwidget)
        self.Sportik_self_place_.setGeometry(QtCore.QRect(1100, 70, 40, 20))
        self.Sportik_self_place_.setObjectName("Sportik_self_place_")
        self.checkBox_self_place_ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_self_place_.setGeometry(QtCore.QRect(1100, 20, 40, 20))
        self.checkBox_self_place_.setText("")
        self.checkBox_self_place_.setChecked(False)
        self.checkBox_self_place_.setObjectName("checkBox_self_place_")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 18))
        self.menubar.setObjectName("menubar")
        self.MainMenuFile = QtWidgets.QMenu(self.menubar)
        self.MainMenuFile.setObjectName("MainMenuFile")
        self.MainMenuAbout = QtWidgets.QMenu(self.menubar)
        self.MainMenuAbout.setObjectName("MainMenuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MainMenuFile.addSeparator()
        self.MainMenuFile.addSeparator()
        self.MainMenuFile.addSeparator()
        self.menubar.addAction(self.MainMenuFile.menuAction())
        self.menubar.addAction(self.MainMenuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Sportik_number_, self.Sportik_fio_)
        MainWindow.setTabOrder(self.Sportik_fio_, self.Sportik_zona1_)
        MainWindow.setTabOrder(self.Sportik_zona1_, self.Sportik_zona2_)
        MainWindow.setTabOrder(self.Sportik_zona2_, self.Sportik_period1_)
        MainWindow.setTabOrder(self.Sportik_period1_, self.Sportik_period2_)
        MainWindow.setTabOrder(self.Sportik_period2_, self.Sportik_period3_)
        MainWindow.setTabOrder(self.Sportik_period3_, self.Sportik_period4_)
        MainWindow.setTabOrder(self.Sportik_period4_, self.Sportik_points_)
        MainWindow.setTabOrder(self.Sportik_points_, self.Sportik_team_place_)
        MainWindow.setTabOrder(self.Sportik_team_place_, self.checkBox_zona2_)
        MainWindow.setTabOrder(self.checkBox_zona2_, self.checkBox_period1_)
        MainWindow.setTabOrder(self.checkBox_period1_, self.checkBox_period2_)
        MainWindow.setTabOrder(self.checkBox_period2_, self.checkBox_period3_)
        MainWindow.setTabOrder(self.checkBox_period3_, self.checkBox_period4_)
        MainWindow.setTabOrder(self.checkBox_period4_, self.checkBox_number_)
        MainWindow.setTabOrder(self.checkBox_number_, self.checkBox_fio_)
        MainWindow.setTabOrder(self.checkBox_fio_, self.checkBox_zona1_)
        MainWindow.setTabOrder(self.checkBox_zona1_, self.checkBox_points_)
        MainWindow.setTabOrder(self.checkBox_points_, self.checkBox_team_place_)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Sportik_zona1_.setItemText(0, _translate("MainWindow", "Zona A"))
        self.Sportik_zona1_.setItemText(1, _translate("MainWindow", "Zona B"))
        self.Sportik_zona1_.setItemText(2, _translate("MainWindow", "Zona C"))
        self.Sportik_zona2_.setItemText(0, _translate("MainWindow", "Zona A"))
        self.Sportik_zona2_.setItemText(1, _translate("MainWindow", "Zona B"))
        self.Sportik_zona2_.setItemText(2, _translate("MainWindow", "Zona C"))
        self.label_number_.setText(_translate("MainWindow", "Номер"))
        self.label_lottery_.setText(_translate("MainWindow", "Жребий"))
        self.label_fio_.setText(_translate("MainWindow", "ФИО спортика"))
        self.label_team_.setText(_translate("MainWindow", "Команда"))
        self.label_rank_.setText(_translate("MainWindow", "Разряд"))
        self.label_zona1_.setText(_translate("MainWindow", "Зона1"))
        self.label_zona2_.setText(_translate("MainWindow", "Зона2"))
        self.label_period1_.setText(_translate("MainWindow", "П 1"))
        self.label_period2_.setText(_translate("MainWindow", "П 2"))
        self.label_period3_.setText(_translate("MainWindow", "П 3"))
        self.label_period4_.setText(_translate("MainWindow", "П 4"))
        self.label_points_.setText(_translate("MainWindow", "Очки"))
        self.label_team_place_.setText(_translate("MainWindow", "Личка"))
        self.label_self_place_.setText(_translate("MainWindow", "Команда"))
        self.MainMenuFile.setTitle(_translate("MainWindow", "Файл"))
        self.MainMenuAbout.setTitle(_translate("MainWindow", "Справка"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
