SET_VER = 1
SET_Q = 18
CLUB_ID = "1A2B-3C4D-5E6F"
SOFT_DB_FILE = "db_competition.db"
SOFT_LAST_OPEN = "1980-06-30"
SOFT_MAIN_WINDOW_SIZE = "1300:500"
COMP_DATA_COMPETITION = "2022-02-24"
COMP_q_tur = 1
COMP_q_period = 4
COMP_q_zone = 1
COMP_q_sector = 1
COMP_d_period = 45
COMP_q_anglers = 15
OTH_PER1 = 13
OTH_PER2 = 3
OTH_PER3 = 40
OTH_PER4 = 999
OTH_PER5 = "abcdefghij"
